<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourierSeeder extends Seeder
{
    public function run(): void
    {
        $bangladeshId = DB::table('countries')->where('code', 'BGD')->value('id');

        $couriers = [
            [
                'name' => 'DHL Express',
                'short_name' => 'DHL',
                'service_type' => 'international',
                'account_number' => 'DHL-ACCT-001',
                'contact_person' => 'DHL Support',
                'contact_phone' => '+8809610010010',
                'contact_email' => 'support@dhl.com',
                'address_line_1' => 'Gulshan Avenue',
                'address_line_2' => null,
                'city' => 'Dhaka',
                'state' => 'Dhaka',
                'postal_code' => '1212',
                'country_id' => $bangladeshId,
                'website' => 'https://www.dhl.com',
                'tracking_url_template' => 'https://www.dhl.com/global-en/home/tracking.html?tracking-id={TRACKING_NO}',
                'supports_documents' => true,
                'supports_parcels' => true,
                'supports_import' => true,
                'supports_export' => true,
                'is_default' => true,
                'is_active' => true,
                'notes' => 'Top preferred courier for LC documents.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'FedEx',
                'short_name' => 'FEDEX',
                'service_type' => 'international',
                'account_number' => 'FEDEX-ACCT-002',
                'contact_person' => 'FedEx Support',
                'contact_phone' => '+8809609666777',
                'contact_email' => 'info@fedex.com',
                'address_line_1' => 'Banani Road 12',
                'address_line_2' => null,
                'city' => 'Dhaka',
                'state' => 'Dhaka',
                'postal_code' => '1213',
                'country_id' => $bangladeshId,
                'website' => 'https://www.fedex.com',
                'tracking_url_template' => 'https://www.fedex.com/apps/fedextrack/?tracknumbers={TRACKING_NO}',
                'supports_documents' => true,
                'supports_parcels' => true,
                'supports_import' => true,
                'supports_export' => true,
                'is_default' => false,
                'is_active' => true,
                'notes' => 'Often used for EU and US buyers.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'UPS',
                'short_name' => 'UPS',
                'service_type' => 'international',
                'account_number' => 'UPS-ACCT-003',
                'contact_person' => 'UPS Support',
                'contact_phone' => '+8809609777888',
                'contact_email' => 'support@ups.com',
                'address_line_1' => 'Kakrail Road',
                'address_line_2' => null,
                'city' => 'Dhaka',
                'state' => 'Dhaka',
                'postal_code' => '1200',
                'country_id' => $bangladeshId,
                'website' => 'https://www.ups.com',
                'tracking_url_template' => 'https://www.ups.com/track?loc=en_US&tracknum={TRACKING_NO}',
                'supports_documents' => true,
                'supports_parcels' => true,
                'supports_import' => true,
                'supports_export' => true,
                'is_default' => false,
                'is_active' => true,
                'notes' => 'Alternative for Europe shipments.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Aramex',
                'short_name' => 'ARAMEX',
                'service_type' => 'international',
                'account_number' => 'ARAMEX-ACCT-004',
                'contact_person' => 'Aramex Support',
                'contact_phone' => '+8809613111000',
                'contact_email' => 'info@aramex.com',
                'address_line_1' => 'Baridhara DOHS',
                'address_line_2' => null,
                'city' => 'Dhaka',
                'state' => 'Dhaka',
                'postal_code' => '1212',
                'country_id' => $bangladeshId,
                'website' => 'https://www.aramex.com',
                'tracking_url_template' => 'https://www.aramex.com/track/shipments/{TRACKING_NO}',
                'supports_documents' => true,
                'supports_parcels' => true,
                'supports_import' => true,
                'supports_export' => true,
                'is_default' => false,
                'is_active' => true,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'TNT Express',
                'short_name' => 'TNT',
                'service_type' => 'international',
                'account_number' => 'TNT-ACCT-005',
                'contact_person' => 'TNT Support',
                'contact_phone' => '+8801711998877',
                'contact_email' => 'support@tnt.com',
                'address_line_1' => null,
                'address_line_2' => null,
                'city' => 'Dhaka',
                'state' => 'Dhaka',
                'postal_code' => null,
                'country_id' => $bangladeshId,
                'website' => 'https://www.tnt.com',
                'tracking_url_template' => 'https://www.tnt.com/express/en_bd/site/tracking.html?cons={TRACKING_NO}',
                'supports_documents' => true,
                'supports_parcels' => true,
                'supports_import' => false,
                'supports_export' => true,
                'is_default' => false,
                'is_active' => true,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Sundarban Courier Service',
                'short_name' => 'SCS',
                'service_type' => 'local',
                'account_number' => null,
                'contact_person' => null,
                'contact_phone' => '+8801730050011',
                'contact_email' => null,
                'address_line_1' => null,
                'address_line_2' => null,
                'city' => 'Dhaka',
                'state' => 'Dhaka',
                'postal_code' => null,
                'country_id' => $bangladeshId,
                'website' => null,
                'tracking_url_template' => 'https://www.sundarbancourierltd.com/tracking?track={TRACKING_NO}',
                'supports_documents' => true,
                'supports_parcels' => true,
                'supports_import' => false,
                'supports_export' => false,
                'is_default' => false,
                'is_active' => true,
                'notes' => 'Frequently used domestic courier.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'SA Paribahan',
                'short_name' => 'SAP',
                'service_type' => 'local',
                'account_number' => null,
                'contact_person' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'address_line_1' => null,
                'address_line_2' => null,
                'city' => 'Dhaka',
                'state' => 'Dhaka',
                'postal_code' => null,
                'country_id' => $bangladeshId,
                'website' => null,
                'tracking_url_template' => null,
                'supports_documents' => true,
                'supports_parcels' => true,
                'supports_import' => false,
                'supports_export' => false,
                'is_default' => false,
                'is_active' => true,
                'notes' => 'Used for parcel shipments within Bangladesh.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Pathao Courier',
                'short_name' => 'PATHAO',
                'service_type' => 'local',
                'account_number' => null,
                'contact_person' => null,
                'contact_phone' => '+8809609668888',
                'contact_email' => null,
                'address_line_1' => null,
                'address_line_2' => null,
                'city' => 'Dhaka',
                'state' => 'Dhaka',
                'postal_code' => null,
                'country_id' => $bangladeshId,
                'website' => null,
                'tracking_url_template' => 'https://pathao.com/courier/tracking/{TRACKING_NO}',
                'supports_documents' => true,
                'supports_parcels' => true,
                'supports_import' => false,
                'supports_export' => false,
                'is_default' => false,
                'is_active' => true,
                'notes' => 'Local city courier.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('couriers')->insert($couriers);
    }
}